### PR TITLE
fix #6, update com.drewnoakes/metadata-extractor to 2.17.0

### LINKED ISSUE #6: extract exif metadata from QuickTime files
First of all, thanks for the library!
I'm trying to use it on `.mp4` files produced by a Sony ZV-1 camera, and it currently doesn't work, because it throws this exception: 
```
com.drew.imaging.ImageProcessingException: File format is not supported
```
To reproduce you can use any `.mov` file [in this page](https://filesamples.com/formats/mov), or I can provide a ~4Mb mp4 file straight out of the ZV-1. 

If that's ok, I can provide a PR that will make it work.

### PR DESCRIPTION
**Pull request by mox601**
This makes it work with QuickTime files (coming out of a Sony ZV-1 camera, I don't know why 🤔), as stated in the issue #6. 
I still have to bump the library version, right? 
Let me know if it looks good!

### CODE REVIEW

**Comment by joshuamiller** [comment]
@mox601 This looks good. If you mark it as ready for review, I'll merge then bump the version and push to Clojars.

**Comment by mox601** [comment]
The PR is now ready for review 🤞 !

**Review by joshuamiller — APPROVED** [review]

**Comment by joshuamiller** [comment]
@mox601 That is merged and pushed to Clojars as version `0.3.0`. Thanks!

**Comment by mox601** [comment]
Thanks @joshuamiller ! 👍

**Pull request merged**
